
name: Run Script

on:
  workflow_dispatch:

jobs:
  build-from-prebuilt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Download youtube.apk
        run: |
          mkdir "build"
          wget "https://github.com/f97/revanced-release/releases/download/youtube/com.google.android.youtube_17.22.36-1529734592_minAPI23.arm64-v8a.armeabi-v7a.x86.x86_64.nodpi._apkmirror.com.apk" -O build/youtube.apk
      
      - name: Execute build-from-prebuilt.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          chmod +x ./build-from-prebuilt.sh
          ./build-from-prebuilt.sh

      # - name: Push revanced.apk to github
      #   run:  |
      #     git config --global user.name 'f97' 
      #     git config --global user.email 'admin@f97.xyz'
      #     git lfs track revanced.apk
      #     git add revanced.apk
      #     git commit -m '⬆️ add revanced.apk'
      #     git push -f

      - name: Upload revanced.apk to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: revanced.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
